build_development:
  extends: .build_template

test_development:
  extends: .test_template
  dependencies:
    - build_development

deploy_development:
  extends: .deploy_template
  dependencies:
    - build_development
  variables:
    NODE_ENV: development
    CF_API_TOKEN: $DEV_CF_API_TOKEN
    CF_ACCOUNT_ID: $DEV_CF_ACCOUNT_ID