lint_development:
  extends: .lint_template

build_development:
  extends: .build_template
  artifacts:
    # Override artifacts: No artifacts declared as build does not generate dist yet
    paths: []

test_development:
  extends: .test_template
  dependencies:
    - build_development

test_coverage_development:
  extends: .test_coverage_template
  dependencies:
    - build_development

deploy_migrate_db_development:
  extends: .deploy_migrate_db_template
  variables:
    NODE_ENV: development
    CF_API_TOKEN: $DEV_CF_API_TOKEN
    CF_ACCOUNT_ID: $DEV_CF_ACCOUNT_ID

deploy_development:
  extends: .deploy_template
  needs:
    - deploy_migrate_db_development
    - build_development
  variables:
    NODE_ENV: development
    CF_API_TOKEN: $DEV_CF_API_TOKEN
    CF_ACCOUNT_ID: $DEV_CF_ACCOUNT_ID

# Manual jobs
manual_update_env_development:
  extends: .manual_update_env_template
  variables:
    NODE_ENV: development
    CF_API_TOKEN: $DEV_CF_API_TOKEN
    CF_ACCOUNT_ID: $DEV_CF_ACCOUNT_ID
