build_development:
  extends: .build_template

test_development:
  extends: .test_template
  dependencies:
    - build_development

deploy_development:
  extends: .deploy_template
  dependencies:
    - build_development
  variables:
    NODE_ENV: development
    CF_API_TOKEN: $DEV_CF_API_TOKEN
    CF_ACCOUNT_ID: $DEV_CF_ACCOUNT_ID

read_secure_file:
  stage: test
  script:
    - echo "Listing secure files in $CI_SECURE_FILES_DIR:"
    - ls -la $CI_SECURE_FILES_DIR || echo "No secure files found!"
    - echo "Attempting to read .dev.vars file:"
    - if [ -f "$CI_SECURE_FILES_DIR/.dev.vars" ]; then
        cat "$CI_SECURE_FILES_DIR/.dev.vars";
      else
        echo "Secure file '.dev.vars' not found in $CI_SECURE_FILES_DIR!";
      fi
  rules:
    - when: always
