module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Enforce a blank line after body or footer
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
    // Ensure header is not too long
    'header-max-length': [2, 'always', 100],
    // Subject and type must not be empty
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    // Allow lowercase or sentence-case subjects (no restriction)
    'subject-case': [0],
    // Restrict commit type to standardized list
    'type-enum': [
      2,
      'always',
      [
        'feat', // New feature
        'fix', // Bug fix
        'docs', // Documentation changes
        'style', // Code style changes (white-space, formatting, etc.)
        'refactor', // Code refactoring (no behavior changes)
        'perf', // Performance improvements
        'test', // Adding tests
        'chore', // Other changes (e.g., tooling, CI/CD)
        'ci', // CI/CD related changes
        'build', // Build process changes
        'revert', // Reverting commits
      ],
    ],
    // Custom rule: Ensure footer follows the Conventional Commits style
    'footer-max-line-length': [2, 'always', 100],
  },
  ignores: [
    // Ignore Cloudflare-specific autogenerated commits
    commit => commit.startsWith('Update wrangler.toml'),
  ],
  defaultIgnores: true, // Keep default ignores (merge and revert commits)
  disableEmoji: false,
}
