export const EXCEPTION_PREFIXES = {
  UNAUTHORIZED: '[UN AUTHORIZATION]',
  FORBIDDEN: '[RESOURCES FORBIDDEN]',
  INTERNAL_SERVER: '[SERVER EXCEPTION]',
  NOT_FOUND: '[RESOURCES NOT FOUND]',
  RATE_LIMIT: '[RATE LIMIT]',
  BAD_REQUEST: '[BAD REQUEST]',
};
