// Generated by Wrangler on Sat Dec 14 2024 14:10:10 GMT+0700 (Indochina Time)
// by running `wrangler types --env-interface CloudflareBindings src/types/worker-configuration.d.ts`

interface CloudflareBindings {
  ENVIRONMENT: string;
  MIXMAX_SNIPPET_API_URL: string;
  MIXMAX_API_TOKEN: string;
  FACEBOOK_GRAPH_HOST: string;
  FACEBOOK_GRAPH_VERSION: string;
  FACEBOOK_APP_ID: string;
  FACEBOOK_APP_SECRET: string;
  INSTAGRAM_GRAPH_HOST: string;
  INSTAGRAM_GRAPH_VERSION: string;
  INSTAGRAM_APP_ID: string;
  INSTAGRAM_APP_SECRET: string;
  SHOPIFY_API_KEY: string;
  SHOPIFY_SECRET_KEY: string;
  FCM_TYPE: string;
  FCM_PROJECT_ID: string;
  FCM_PRIVATE_KEY_ID: string;
  FCM_PRIVATE_KEY: string;
  FCM_CLIENT_EMAIL: string;
  FCM_CLIENT_ID: string;
  FCM_AUTH_URI: string;
  FCM_TOKEN_URI: string;
  FCM_AUTH_PROVIDER_X509_CERT_URL: string;
  FCM_CLIENT_X509_CERT_URL: string;
  FCM_UNIVERSE_DOMAIN: string;
  FE_HOST: string;
  BE_HOST: string;
  BE_HOST_API: string;
  BE_HOST_PUBLIC: string;
  BE_HOST_WEBHOOK: string;
  PUBLIC_R2_URL: string;
  DEV_BUCKET: R2Bucket;
  DB: D1Database;
}
